name: Web App CD

on:
  workflow_run: 
    workflow: [.NET Core CI"]
    types: [completed]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.0.5
      with:
        # Artifact name
        name: webapp
        # Destination path
        path: artifact
    - name: Display structure of downloaded files
      run: ls -R
      working-directory: artifact
