name: "Web App CD"

on:
  pull_request:
    types: [closed]

env:
  APP_SVC_NAME: wviriyaarm 
    
jobs:
  dev_release:
    if: github.event.pull_request.merged == true
    name: Dev Release
    runs-on: ubuntu-latest
    environment: dev
    env: 
      SLOT: dev
    steps:
    - uses: actions/checkout@v2

    - name: Download workflow artifact
      uses: dawidd6/action-download-artifact@v2.9.0
      with:
        # Workflow name
        workflow: dotnet_build.yml
        pr: ${{github.event.pull_request.number}}
        # Artifact name (download all artifacts in not specified)
        name: webapp
        # Where to unpack the artifact
        path: ./artifact
    
    - name: Display structure of downloaded files
      run: ls -R
      working-directory: ./artifact
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Azure WebApp
      uses: Azure/webapps-deploy@v2
      with:
        # Name of the Azure Web App
        app-name: ${{ env.APP_SVC_NAME }}
        slot-name: dev
        # Applies to Web App only: Path to package or folder. *.zip, *.war, *.jar or a folder to deploy
        package: ./artifact
  
  test_release:
    if: github.event.pull_request.merged == true
    name: Test Release
    runs-on: ubuntu-latest
    environment: test
    steps:
    - uses: actions/checkout@v2

    - name: Download workflow artifact
      uses: dawidd6/action-download-artifact@v2.9.0
      with:
        # Workflow name
        workflow: dotnet_build.yml
        pr: ${{github.event.pull_request.number}}
        # Artifact name (download all artifacts in not specified)
        name: webapp
        # Where to unpack the artifact
        path: ./artifact
    
    - name: Display structure of downloaded files
      run: ls -R
      working-directory: ./artifact
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Azure WebApp
      uses: Azure/webapps-deploy@v2
      with:
        # Name of the Azure Web App
        app-name: ${{ env.APP_SVC_NAME }}
        slot-name: test
        # Applies to Web App only: Path to package or folder. *.zip, *.war, *.jar or a folder to deploy
        package: ./artifact
  
  prod_release:
    if: github.event.pull_request.merged == true
    name: Prod Release
    runs-on: ubuntu-latest
    environment: prod
    steps:
    - uses: actions/checkout@v2

    - name: Download workflow artifact
      uses: dawidd6/action-download-artifact@v2.9.0
      with:
        # Workflow name
        workflow: dotnet_build.yml
        pr: ${{github.event.pull_request.number}}
        # Artifact name (download all artifacts in not specified)
        name: webapp
        # Where to unpack the artifact
        path: ./artifact
    
    - name: Display structure of downloaded files
      run: ls -R
      working-directory: ./artifact
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Azure WebApp
      uses: Azure/webapps-deploy@v2
      with:
        # Name of the Azure Web App
        app-name: ${{ env.APP_SVC_NAME }}
        # Applies to Web App only: Path to package or folder. *.zip, *.war, *.jar or a folder to deploy
        package: ./artifact
