name: "Web App CD"

on:
  pull_request:
    types: [closed]
    
jobs:
  publish:
    if: github.event.pull_request.merged == true
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.0.5
      with:
        # Artifact name
        name: webapp
        # Destination path
        path: artifact
    
    - name: Display structure of downloaded files
      run: ls -R
      working-directory: artifact
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Azure WebApp
      uses: Azure/webapps-deploy@v2
      with:
        # Name of the Azure Web App
        app-name: azninja-armdemo
        slot-name: dev
        # Applies to Web App only: Path to package or folder. *.zip, *.war, *.jar or a folder to deploy
        package: webapp
